language: python
python:
- "3.5"
matrix:
  include:
    - os: linux
      sudo: False
install:
- pip install -r requirements.txt
script:
- nosetests pychrom/tests/ -v --with-coverage --cover-package=pychrom