language: python
python:
- "3.5"
matrix:
  include:
    - os: linux
      sudo: True
before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX
- sudo apt-get install libhdf5-serial-dev hdf5-tools
- sudo apt-get install liblapack-dev
install:
- pip install -r requirements.txt
script:
- gcc --version
- nosetests pychrom/tests/ -v --with-coverage --cover-package=pychrom