language: python
python:
- "3.5"
matrix:
  include:
    - os: linux
      sudo: False

before_install:
before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX
install:
- pip install -r requirements.txt
script:
- gcc --version
- nosetests pychrom/tests/ -v --with-coverage --cover-package=pychrom